application:
  subdomain: cloudfalred-web
  background_task: true
  public_path:
{{if .U.enable_basic_auth}}
    - /
{{end}}

  upstreams:
    - location: /
      backend: http://host.lzcapp:14333/
services:
  cloudfalred-web:
    network_mode: host
    # upstream: wisdomsky/cloudflared-web:2026.9.1
    image: docker.1ms.run/wisdomsky/cloudflared-web:2026.9.1
    binds:
      - /lzcapp/var/config:/config
    environment:
      - PROTOCOL={{.U.protocol}}
{{if .U.enable_basic_auth}}
      - BASIC_AUTH_USER={{.U.basic_auth_user}}
      - BASIC_AUTH_PASS={{.U.basic_auth_password}}
{{end}}
