package: lazycat.community.app.cloudfalred-web
version: 2025.9.0
name: Cloudflared
description: "Cloudflared Tunnel Web"
min_os_version: "1.3.8"
homepage: https://github.com/dockers-x/Cloudflared-web
author: dockers-x
locales:
  zh:
    description: "带 Web 管理界面的 Cloudflare Tunnel 客户端"
    name: Cloudflared
  en:
    description: "Cloudflared Tunnel Web"
    name: Cloudflared
